import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
 await page.goto('http://localhost:5173/');
 await page.getByRole('textbox', { name: 'שם משתמש' }).click();
 await page.getByRole('textbox', { name: 'שם משתמש' }).fill('מוישי');
 await page.getByRole('button', { name: 'כניסה למערכת' }).click();
 await page.getByRole('link', { name: 'לקוחות' }).click();
 await page.getByRole('button', { name: '+ לקוח חדש' }).click();
 await page.locator('input[name="fullName"]').click();
 await page.locator('input[name="fullName"]').fill('אלימלך ארליך');
 await page.locator('input[name="identityId"]').click();
 await page.locator('input[name="identityId"]').fill('315592527');
 await page.locator('input[name="phoneNumber"]').click();
 await page.locator('input[name="phoneNumber"]').fill('0506569203');
 await page.locator('input[name="address"]').click();
 await page.locator('input[name="address"]').fill('פחד יצחק 17 ביתר עילית');
 await page.locator('input[name="email"]').click();
 await page.locator('input[name="email"]').fill('ee525566@gmail.com');
 await page.locator('input[name="businessName"]').click();
 await page.locator('input[name="businessName"]').fill('אלימלך ארליך');
 await page.locator('input[name="businessID"]').click();
 await page.locator('input[name="businessID"]').fill('315592527');
 await page.locator('input[name="openingDate"]').fill('2026-04-01');
 await page.getByRole('combobox').selectOption('מורשה');
 await page.locator('input[name="occupation"]').click();
 await page.locator('input[name="occupation"]').fill('פיתוח תוכנה');
 await page.locator('textarea[name="businessDescription"]').click();
 await page.locator('textarea[name="businessDescription"]').fill('פיתוח תוכנה');
 await page.getByRole('checkbox', { name: 'טיפול בביטוח לאומי' }).check();
 await page.locator('select[name="newInsuranceCase"]').selectOption('false');
 await page.locator('select[name="newInsuranceCase"]').selectOption('true');
 await page.locator('input[name="insurancePrepayment"]').click();
 await page.locator('input[name="insurancePrepayment"]').fill('450');
 await page.locator('input[name="workHours"]').click();
 await page.locator('input[name="workHours"]').fill('150');
 await page.getByRole('checkbox', { name: 'טיפול במס הכנסה' }).check();
 await page.locator('select[name="newItCase"]').selectOption('false');
 await page.locator('select[name="newItCase"]').selectOption('true');
 await page.locator('input[name="incomeTaxPrepayment"]').click();
 await page.locator('input[name="incomeTaxPrepayment"]').fill('2500');
 await page.locator('input[name="annualTurnover"]').click();
 await page.locator('input[name="annualTurnover"]').fill('250000');
 await page.locator('select[name="repType"]').selectOption('משני');
 await page.locator('select[name="repType"]').selectOption('ראשי');
 await page.getByRole('checkbox', { name: 'טיפול במע״מ' }).check();
 await page.locator('select[name="newVatCase"]').selectOption('false');
 await page.locator('select[name="newVatCase"]').selectOption('true');
 await page.locator('select[name="employsWorkers"]').selectOption('yes');
 await page.locator('select[name="employsWorkers"]').selectOption('no');
 await page.locator('select[name="employsWorkers"]').selectOption('yes');
 await page.locator('input[name="needsDeductionsFile"]').uncheck();
 await page.locator('input[name="needsDeductionsFile"]').check();
 await page.locator('input[name="setupFee"]').click();
 await page.locator('input[name="setupFee"]').click();
 await page.locator('input[name="setupFee"]').click();
 await page.locator('input[name="setupFee"]').click();
 await page.locator('input[name="setupFee"]').fill('1000');
 await page.locator('input[name="monthlyFee"]').click();
 await page.locator('input[name="monthlyFee"]').click();
 await page.locator('input[name="monthlyFee"]').fill('550');
 await page.getByRole('button', { name: 'כן' }).click();
 await page.getByRole('button', { name: 'לא' }).click();
 await page.locator('textarea[name="comments"]').click();
 await page.locator('textarea[name="comments"]').fill('הלקוח חדש, לדאוג שיקבל שירות טוב');
 page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'שמור לקוח והפעל אוטומציית משימות' }).click();

});